sehri_time: "04:30"
iftar_time: "18:45"

free_food_sehri:
  item: "BREAD"
  amount: 5

free_food_iftar:
  item: "COOKED_CHICKEN"
  amount: 5

money_reward: 10000

scoreboard_frames:
  - "Â§6ğŸŒ™ Ramadan Blessings ğŸŒ™"
  - "Â§bğŸŒ™ Ramadan Blessings ğŸŒ™"
